/**
 * Helpers for extracting structured sections from taste_profiles.content
 * (the markdown blob generated by lib/taste-profile/generate.js).
 */

const PRIVATE_MARKER = '## Curators They Subscribe To';

/**
 * Return the portion of the taste profile that is safe to expose publicly —
 * everything before the "## Curators They Subscribe To" heading. Subscriptions
 * are a consumption signal, not a taste signal, and are kept curator-private.
 *
 * @param {string | null | undefined} content
 * @returns {string | null}
 */
export function extractPublicSections(content) {
  if (!content || typeof content !== 'string') return null;
  const cutIndex = content.indexOf(PRIVATE_MARKER);
  const sliced = cutIndex !== -1 ? content.slice(0, cutIndex) : content;
  const trimmed = sliced.trimEnd();
  return trimmed.length > 0 ? trimmed : null;
}

/**
 * Extract the body of the "## Voice & Style" section from the taste profile
 * markdown. Returns everything between that heading and the next "## "
 * heading (or end of string). Returns null if the section is missing or empty.
 *
 * @param {string | null | undefined} content
 * @returns {string | null}
 */
export function extractVoiceAndStyle(content) {
  if (!content || typeof content !== 'string') return null;
  const heading = '## Voice & Style';
  const startIdx = content.indexOf(heading);
  if (startIdx === -1) return null;
  const bodyStart = startIdx + heading.length;
  const rest = content.slice(bodyStart);
  const nextHeadingIdx = rest.search(/\n## /);
  const body = nextHeadingIdx === -1 ? rest : rest.slice(0, nextHeadingIdx);
  const trimmed = body.trim();
  return trimmed.length > 0 ? trimmed : null;
}
